### PR TITLE
Update test suite to get tests passing again

### PR DESCRIPTION
**Pull request by danielbachhuber**
* Ran `wp scaffold package-tests` to get test suite to latest
* Updated version in `features/check-core-update.feature` to latest

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@schlessera This looks funky:

```
[ErrorException]                                                                                                                          
  include_once(/home/travis/build/wp-cli/doctor-command/php/WP_CLI/AutoloadSplitter.php): failed to open stream: No such file or directory
```

Why would the path be incorrect in this manner?

**Comment by schlessera** [comment]
I fixed the issue so that the tests run now, but not in a satisfying way for now. See https://github.com/wp-cli/autoload-splitter/issues/5 for the problem to solve.

**Comment by schlessera** [comment]
Still fails, now because of a plugin update warning:
```
...................................................................... 70
...................................................................... 140
...................................................................... 210
.......................................F...................F----...... 280
...............................................................
(::) failed steps (::)
01. name	status	message
    plugin-update	warning	1 plugin has an update available.
    In step `Then STDOUT should be a table containing rows:'. # features/steps/then.php:44
    From scenario `Plugins are up to date'.                   # features/check-plugin-update.feature:11
    Of feature `Check whether plugins are up to date'.        # features/check-plugin-update.feature
02. $ wp doctor check --all --spotlight
    name	status	message
    plugin-update	warning	1 plugin has an update available.
    
    cwd: /tmp/wp-cli-test-run-59097a78b71457.24786200/
    exit status: 0
    In step `Then STDOUT should be:'.                                # features/steps/then.php:15
    From scenario `Use --spotlight to focus on warnings and errors'. # features/check.feature:3
    Of feature `Basic check usage'.                                  # features/check.feature
66 scenarios (64 passed, 2 failed)
343 steps (337 passed, 4 skipped, 2 failed)
4m33.193s
```

**Comment by danielbachhuber** [comment]
@schlessera This is fixed now

**Pull request merged**
